### ISSUE TITLE
GCE Ingress (GLBC) needs improved federation handling at ingress deletion time

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#109]
<a href="https://github.com/csbell"><img src="https://avatars1.githubusercontent.com/u/23373339?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [csbell](https://github.com/csbell)**
_Saturday Mar 04, 2017 at 00:02 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/42511_

----

While GLBC has been coaxed to handle duplicate Ingress objects at creation time, it needs more logic to correctly handle deletion of federated ingresses. Currently, deleting one of the ingress objects outside of  federation will cause the entire ingress to be torn down. Eventually the federated controller re-creates the ingress object but the downtime should be omitted altogether. Possible solutions include some form of adhoc refcounting mechanism or augmenting GLBC to notice that there are more than one relevant forwarding rules attached to an ingress object at deletion time. Details and design to be hashed out still.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/marun"><img src="https://avatars3.githubusercontent.com/u/451477?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marun](https://github.com/marun)**
_Monday Jun 12, 2017 at 20:34 GMT_

----

Given that this appears to require considerable work to accomplish, I'm moving to 1.8.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/k8s-merge-robot"><img src="https://avatars0.githubusercontent.com/u/13653959?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k8s-merge-robot](https://github.com/k8s-merge-robot)**
_Thursday Sep 07, 2017 at 08:04 GMT_

----

[MILESTONENOTIFIER] Milestone Labels Incomplete

@csbell

**Action required**: This issue requires label changes.  If the required changes are not made within 1 day, the issue will be moved out of the v1.8 milestone.

kind: Must specify at most one of ['kind/bug', 'kind/feature', 'kind/cleanup'].
priority: Must specify at most one of ['priority/critical-urgent', 'priority/important-soon', 'priority/important-longterm'].

<details>
Additional instructions available <a href="https://github.com/kubernetes/community/blob/master/contributors/devel/release/issues.md">here</a>
</details>

**Comment by irfanurrehman** [comment]
cc @csbell

**Comment by csbell** [comment]
All work in this area being pursued through [kubemci](https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress).
/close
