### ISSUE TITLE
Introduce a kubefed flag to allow time outs

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#118]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [madhusudancs](https://github.com/madhusudancs)**
_Wednesday Mar 15, 2017 at 05:14 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/43123_

----

Today `kubefed` waits infinitely for its operations to complete. This is suboptimal. Our tests, for example, take about 15 hours before the overall timeout. Users probably face the same situation. We should introduce a hidden flag to allow time outs in tests for now and then promote it to a real flag and document it.

This is a sub-issue of issue #41725.

cc @kubernetes/sig-federation-feature-requests @csbell

**Comment by irfanurrehman** [comment]
<a href="https://github.com/irfanurrehman"><img src="https://avatars0.githubusercontent.com/u/10027921?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [irfanurrehman](https://github.com/irfanurrehman)**
_Monday Mar 20, 2017 at 11:47 GMT_

----

@madhusudancs, does it make more sense to have the default behavior as time out at some time, which can be configured using this flag including some way to define try-forever?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [madhusudancs](https://github.com/madhusudancs)**
_Monday Mar 20, 2017 at 18:31 GMT_

----

Yeah, changing the default to some fixed duration, although a longer one, in the future might be a good idea.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/irfanurrehman"><img src="https://avatars0.githubusercontent.com/u/10027921?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [irfanurrehman](https://github.com/irfanurrehman)**
_Saturday Apr 08, 2017 at 14:03 GMT_

----

I somehow remember @perotinus taking this up earlier.
@perotinus do u have an open PR for this.. ? (could not find one).

**Comment by irfanurrehman** [comment]
<a href="https://github.com/perotinus"><img src="https://avatars1.githubusercontent.com/u/5122391?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [perotinus](https://github.com/perotinus)**
_Monday Apr 10, 2017 at 17:10 GMT_

----

@irfanurrehman I don't think I have an open PR for this in particular, though you are correct that #42296 does add a default timeout for slower init operations. It shouldn't be too hard to make that configurable via flag in a future PR.

**Comment by irfanurrehman** [comment]
cc @madhusudancs

**Comment by leahnp** [comment]
@irfanurrehman  - regarding the bot comment above, do I need to indicate somewhere this issue is actively being worked on (I don't understand the "/remove-lifecycle stale" context)? 

Also it appears I cannot assign this to myself.

**Comment by irfanurrehman** [comment]
The bot keeps looking for issues and PRs which have been inactive for 90+ days, if it finds such, it tags them as stale and closes them after 30 more days. This is to keep the repos clean from those issues/PRs which don't get worked on. We can keep them alive by removing that label.
Once you have couple of PRs under your belt, you become eligible to get added to the k8s org (become a member), post that you can be one of the assignees. Until then I can proxy assign myself, to reflect that the issue is being worked on.
/assign
