### ISSUE TITLE
pr:pull-kubernetes-federation-e2e-gce flaked 94 times in the past week

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#12]
<a href="https://github.com/fejta-bot"><img src="https://avatars1.githubusercontent.com/u/30488982?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fejta-bot](https://github.com/fejta-bot)**
_Wednesday Sep 13, 2017 at 22:28 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/52455_

----

### Flaky Job: pr:pull-kubernetes-federation-e2e-gce
 Flakes in the past week: **94**
 Consistency: **86.80%**

#### Flakiest tests by flake count:
| Test | Flake Count |
| --- | --- |
| Federation Up | 95 |
| DumpFederationLogs | 89 |
| FederationTest | 5 |

[Flakiest Jobs](https://storage.googleapis.com/k8s-metrics/flakes-latest.json)

**Comment by shashidharatd** [comment]
This is no longer relevant and we have a separate PR job now.
/close
