### ISSUE TITLE
Prevent users from deleting pods serving live traffic

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#122]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nikhiljindal](https://github.com/nikhiljindal)**
_Wednesday Mar 22, 2017 at 00:01 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/43487_

----

Problem:
Users today can run `kubectl delete rs` that does cascading deletion by default and hence will also end up deleting all the pods, even though they might have been serving live traffic.
The problem is even more severe in the case of federation since the deletion impacts multiple clusters and can cause global outages.

One possible solution:
When user creates an ingress (or service) targeting an rs, we should add a finalizer to the backend pods for that ingress to ensure that they cant be deleted unless the ingress is deleted.
Once user deletes the ingress, they can go ahead and delete the rs.

cc @quinton-hoole @bgrant0607 @kubernetes/sig-federation-feature-requests

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Wednesday Mar 22, 2017 at 00:06 GMT_

----

We will need to introduce this functionality in a backward compatible way i.e we cant change the existing ingress implementation to do this. Users today expect to delete rs before deleting the ingress and we should not break that.

What we can do is if users add a particular annotation to their ingress, then that prevents deleting the corresponding rs before the ingress (i.e users have to explicitly opt in to this).

Since federation is still new, we can update federation to add that annotation to federated ingressed by default.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/liggitt"><img src="https://avatars0.githubusercontent.com/u/980082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [liggitt](https://github.com/liggitt)**
_Wednesday Mar 22, 2017 at 01:12 GMT_

----

isn't this working as designed? graceful deletion allows pods time to finish serving requests

**Comment by irfanurrehman** [comment]
<a href="https://github.com/kargakis"><img src="https://avatars3.githubusercontent.com/u/3900799?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kargakis](https://github.com/kargakis)**
_Wednesday Mar 22, 2017 at 01:19 GMT_

----

We already have mechanisms for avoiding outages (maxUnavailable in Deployments/DaemonSets, PDB). Why aren't those enough?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Wednesday Mar 22, 2017 at 01:33 GMT_

----

Sorry for not being clear, this is to prevent outages by developer running `kubectl delete rs` or `kubectl delete deployment`. maxUnavailable will not help in that case.

Graceful deletion will help so that existing requests will be handled gracefully but not for future requests.

This is helpful in the scenario when developer thought that the rs or deployment is not serving traffic and hence deleted it, but actually it was serving user traffic. Also helpful when `kubectl delete` command is run unintentionally - causing an outage.


A service or ingress for the rs or deployment shows an intent of receiving traffic for those pods, which we can use to detect a potential outage.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/kargakis"><img src="https://avatars3.githubusercontent.com/u/3900799?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kargakis](https://github.com/kargakis)**
_Wednesday Mar 22, 2017 at 01:53 GMT_

----

Isn't this a more general problem related to any kind of mutation? For example, by scaling up a stateful app I could still cause an outage. Or by pushing bad config, although in this case, correctly configured controllers may incur only partial unavailability.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/smarterclayton"><img src="https://avatars0.githubusercontent.com/u/1163175?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [smarterclayton](https://github.com/smarterclayton)**
_Wednesday Mar 22, 2017 at 23:57 GMT_

----

The solution is to not let people delete.  99% of production use cases don't involve deletion.  99% of dev / test / first time user use cases do.  kubectl allowing you to delete things is bad in production.

This is what deletion protection was intended to solve, as well as various UI improvements that require special action to delete anything.  Services, ingress, secrets, etc.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Thursday Mar 23, 2017 at 18:12 GMT_

----

> Isn't this a more general problem related to any kind of mutation? For example, by scaling up a stateful app I could still cause an outage. Or by pushing bad config, although in this case, correctly configured controllers may incur only partial unavailability.

I agree that there are other scenarios that can cause outages and the proposed mechanism does not solve all of them. But I think its still valuable since it solves a particular scenario.
Am open to any other potential solutions. 

> The solution is to not let people delete. 99% of production use cases don't involve deletion. 99% of dev / test / first time user use cases do. kubectl allowing you to delete things is bad in production.

Yes its not as common as other operations, but resources do need to be deleted. Outages in staging are bad as well :)

> 
> This is what deletion protection was intended to solve, as well as various UI improvements that require special action to delete anything. Services, ingress, secrets, etc.

@smarterclayton By deletion protection, do you mean RBAC and restricted access for DELETE operation or is there something else as well?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/smarterclayton"><img src="https://avatars0.githubusercontent.com/u/1163175?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [smarterclayton](https://github.com/smarterclayton)**
_Thursday Mar 23, 2017 at 20:34 GMT_

----

Delete protection was an annotation on the resource that the CLI or
web UI would respect that requires you to confirm deletion.  It would
start client only and apply to all clients.

A second level would be requiring higher permissions to delete in some
namespaces, but that is not likely to solve the real problem.

A third level might be "lock" for human driven operations in a namespace.

**Comment by irfanurrehman** [comment]
cc @nikhiljindal

**Comment by tsmgeek** [comment]
I think that this would still be a good idea to implement somehow if only at the deployment/statefulset/service and not cascaded.

Same as Termination Protection on say AWS, just prevent it being deleted unless the flag is removed, of course if its a deployment then users delete the pod it will just recreate it anyway which is fine.

/remove-lifecycle rotten
/reopen
