### ISSUE TITLE
Feature Request: API should return cluster name

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#132]
<a href="https://github.com/tback"><img src="https://avatars0.githubusercontent.com/u/83432?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tback](https://github.com/tback)**
_Wednesday Apr 26, 2017 at 13:41 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/44954_

----

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
api cluster name, api get cluster name, cluster name programatically 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I want to get the name of the current kubernetes cluster from the api so I can make it available in helm. My usecase is, that I want to annotate automatic backups with the clustername so I don't get name conflicts.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/liggitt"><img src="https://avatars0.githubusercontent.com/u/980082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [liggitt](https://github.com/liggitt)**
_Wednesday Apr 26, 2017 at 17:22 GMT_

----

what cluster name are you referring to?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/tback"><img src="https://avatars0.githubusercontent.com/u/83432?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tback](https://github.com/tback)**
_Wednesday Apr 26, 2017 at 20:04 GMT_

----

The one that is shown in `gcloud container clusters list`. Maybe this name isn't currently known inside the cluster, but it'd be great if it was.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/liggitt"><img src="https://avatars0.githubusercontent.com/u/980082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [liggitt](https://github.com/liggitt)**
_Wednesday Apr 26, 2017 at 20:08 GMT_

----

> Maybe this name isn't currently known inside the cluster, but it'd great if it was.

It is not.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/tback"><img src="https://avatars0.githubusercontent.com/u/83432?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tback](https://github.com/tback)**
_Wednesday Apr 26, 2017 at 20:35 GMT_

----

Drats. Did that happen by choice or by accident? Is there a different name or unique identifier available for a cluster? Is there any chance this'll get implemented?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/zytek"><img src="https://avatars1.githubusercontent.com/u/3696278?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zytek](https://github.com/zytek)**
_Wednesday Apr 26, 2017 at 21:57 GMT_

----

In our use case (clusters in AWS managed by kops) you could 'guess' the cluster name from DNS endpoint (like api.NAME.kubernetes.example.com)

**Comment by irfanurrehman** [comment]
<a href="https://github.com/liggitt"><img src="https://avatars0.githubusercontent.com/u/980082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [liggitt](https://github.com/liggitt)**
_Thursday Apr 27, 2017 at 05:15 GMT_

----

> Is there a different name or unique identifier available for a cluster?

Not one that is provided to, known, or used by the kubernetes processes that make up the cluster, no.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/kargakis"><img src="https://avatars3.githubusercontent.com/u/3900799?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kargakis](https://github.com/kargakis)**
_Sunday May 21, 2017 at 10:57 GMT_

----

@kubernetes/sig-federation-misc

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Monday May 22, 2017 at 21:28 GMT_

----

Kubernetes Cluster Federation has the concept of a cluster name for each cluster which is a member of a Federation.  But it is only known to the federation, not to each cluster. And there is in fact a cluster-id field in the ObjectMeta of every Kubernetes object.    But it is not populated by default.  It is there in order that the Federation control plane can populate it to distinguish API objects originating from different clusters.

It does seem like it would be useful for each cluster to know it's name, but it's not clear to me how this should be exposed, where and how it should be defined, and whether it needs to be unique for all clusters (and if so, how to ensure uniqueness).

**Comment by irfanurrehman** [comment]
<a href="https://github.com/jfoy"><img src="https://avatars0.githubusercontent.com/u/171695?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jfoy](https://github.com/jfoy)**
_Saturday Jun 17, 2017 at 21:45 GMT_

----

@quinton-hoole To further confuse things, kube-controller-manager accepts a `--cluster-name` argument which is used in various places by cloudproviders. 

A formal cluster name as part of the API would be very useful to us, too. In the absence of this property, we're left with various templating hacks at deployment time.  Two use cases that come to mind immediately are:
1. A configuration backup daemon, which needs to push cluster-specific artifacts to some external store.
2. Log and metric collectors, which want to annotate outbound streams with a cluster identifier. 

To my mind, cluster name isn't strictly a federation issue, but a core API design question. Has this idea already been considered and rejected? I haven't found much discussion around it.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/ereOn"><img src="https://avatars1.githubusercontent.com/u/585131?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ereOn](https://github.com/ereOn)**
_Thursday Jul 06, 2017 at 20:58 GMT_

----

I currently manage to get the GKE cluster name by querying the following URL:

```
curl http://metadata/computeMetadata/v1/instance/attributes/cluster-name -H "Metadata-Flavor: Google"
```

Is this not supposed to work ? Or is it GKE specific and not tied to Kubernetes ?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/magescher"><img src="https://avatars2.githubusercontent.com/u/5951422?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [magescher](https://github.com/magescher)**
_Monday Jul 10, 2017 at 18:26 GMT_

----

Using the Python API, I get the current cluster name as follows:
```python
from kubernetes import config

cluster_config = config.kube_config.list_kube_config_contexts()
print cluster_config
([{'name': 'minikube', 'context': {'cluster': 'minikube', 'user': 'minikube'}}], {'name': 'minikube', 'context': {'cluster': 'minikube', 'user': 'minikube'}})

cluster_name = cluster_config[1]['context']['cluster']
print cluster_name
minikube

```

**Comment by irfanurrehman** [comment]
<a href="https://github.com/liggitt"><img src="https://avatars0.githubusercontent.com/u/980082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [liggitt](https://github.com/liggitt)**
_Monday Jul 10, 2017 at 18:29 GMT_

----

> Using the Python API, I get the current cluster name as follows

That's just the name of the cluster stanza in your local kubeconfig file, and doesn't have any bearing on the server's view of the world

**Comment by irfanurrehman** [comment]
<a href="https://github.com/geekofalltrades"><img src="https://avatars1.githubusercontent.com/u/6486742?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geekofalltrades](https://github.com/geekofalltrades)**
_Friday Oct 20, 2017 at 20:04 GMT_

----

If clusters don't have names that they know about, then how does the `kubernetes.io/cluster/<cluster-name>=owned` tag used by the AWS cloud provider work?

**Comment by irfanurrehman** [comment]
cc @tback

**Comment by RochesterinNYC** [comment]
Noticed that there are third party services like signalfx that would benefit from being able to programmatically fetch the cluster name and not have to have that passed into config/deployment manifests: https://github.com/signalfx/integrations/blob/1348c09a3b0c192ce5c43430bfe7bf200b766685/signalfx-agent/kubernetes/signalfx-agent.configmap.yml#L13 https://github.com/signalfx/integrations/blob/1348c09a3b0c192ce5c43430bfe7bf200b766685/signalfx-agent/kubernetes/agent-master.yaml#L12

**Comment by briansmith** [comment]
Please reopen this issue. It would help the tools I work on, and I'm sure others, to be able to get this information from the Kubernetes API.

**Comment by nikhita** [comment]
> Please reopen this issue. It would help the tools I work on, and I'm sure others, to be able to get this information from the Kubernetes API.

/reopen

**Comment by kwerey** [comment]
Just a quick note to echo @RochesterinNYC & say this would be handy for all kinds of tooling.

My particular use case is wanting to grab a value for monitoring/logging: I'd much rather report a name value direct from k8s than have to keep environment-specific data in a config as code file that's otherwise generic & applicable across environments and regions!
