### ISSUE TITLE
Error launching Jobs in federation

### ISSUE THREAD

**Issue by wynro** [kubernetes/federation#156]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I tried to launch a Job in a federation, and instead of accepting the Job and scheduling it, the server answered with the error code:

    error: error validating "pi.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"batch", Version:"v1", Kind:"Job"}; if you choose to ignore these errors, turn validation off with --validate=false

If you turn off validation with `--validate=false`, the answer is:

    error: unable to recognize "pi.yaml": no matches for batch/, Kind=Job

**What you expected to happen**:

I expected the federation API server to accept the Job and launch it

**How to reproduce it (as minimally and precisely as possible)**:

I used the example job in kubernetes.io documentation:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

Saved in a file called `pi.yaml`, and tried to launch the job with the command

    kubectl --context=federation create -f ./pi.yaml

**Anything else we need to know?**:

Initially I thought that the problem was in the apiVersion+Kind combination, but the documentation (https://kubernetes.io/docs/tasks/administer-federation/job) says "The API for federated jobs is fully compatible with the API for traditional Kubernetes jobs. You can create a job by sending a request to the federation apiserver. ". If this is an error on my part, I would suggest changing that piece of documentation.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Kubernetes installed in a local network of physical machines. Every master and slave is a physical node. Two clusters, both with one master and 2 slaves, and another master for the federation cluster.
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux <HOSTNAME REDACTED> 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
Manual installation of Kubernetes from last Github release (At the time of deployment)
Manual installation of the federation as described in https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed
- Others:
Nothing

**Comment by irfanurrehman** [comment]
@wynro, apologies for delayed response. The jobs API is not enabled in federation-apiserver by default.
To be able to use the jobs api you need to enable it explicitly while starting the apiserver. If you are deploying the control plane using `kubefed` you can use `--apiserver-arg-overrides="--runtime-config=api/all=true"` as an additional argument to do the same. Please update if and when it works for you.

**Comment by wynro** [comment]
I have recreated the federation with the described option and Jobs work fine. I guess the problem was related with #198. Considering this, I'll close this issue.
