### ISSUE TITLE
No public fcp image can be downloaded

### ISSUE THREAD

**Issue by ggaaooppeenngg** [kubernetes/federation#163]
I found hyperkube is replaced by fcp, and kubefed supports fcp now, but I found no open image in gcr.io, how can I mannually make a fcp image?
Does federation have SIG group?

**Comment by irfanurrehman** [comment]
Relevant to #192. Should be fixed ASAP.

**Comment by mastamark** [comment]
@ggaaooppeenngg - I was able to get going building with my 1.9.x clusters from master and pushing fcp to a dockerhub repo following the steps here:  https://github.com/kubernetes/federation/pull/186/files#diff-07b732fa7b580c0786ac5cc8384fc5ebR15

**Comment by irfanurrehman** [comment]
@ggaaooppeenngg closing this as the official image is now available at `gcr.io/k8s-jkns-e2e-gce-federation/fcp-amd64`.
/close
