### ISSUE TITLE
Failed to delete deployment in federation cluster

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/federation#166]
I have a federation cluster with two clusters, after the deployment was created, it was distributed to two clusters equally with default policy. Such as I have 6 replicas in my deployment and the federation will create 3 replicas in each cluster. 

But when I try to delete the federation deployment, it always failed due to timeout error.

```
error: error when stopping "./lb-nginx.yaml": time out waiting for the condition.
```

Also checked logs for federation apiserver and controller manager, no error found.

I was using kubernetes 1.8.3.

**Comment by Blasterdick** [comment]
Bump. Is there any news? Seems like a situation isn't changed.

**Comment by mastamark** [comment]
I believe this is the same issue:  https://github.com/kubernetes/federation/issues/215

**Comment by prasanna12510** [comment]
on deleting the deployment from federation it doesnt delete the corresponding records created in route53 console
