### ISSUE TITLE
Load-balance cross cluster should support local clusters

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/federation#169]
Now the federated service creates a separate service shard in each underlying cluster in the federation. And to create DNS records for cross-cluster service discovery, federation depends on the load balancer addresses allocated by the cluster service shards.But most of the local clusters do not have a load balancer implementation, federation should support load balancer for multiple local clusters.

/cc @quinton-hoole comments for this? Thanks!

**Comment by bputt** [comment]
Referencing another issue that was closed in favor of this one: https://github.com/kubernetes/kubernetes/issues/58974

**Comment by bputt** [comment]
Also, when adding the label ```priority/important-longterm```, how far out in the future do you expect it to implement this?

**Comment by bputt** [comment]
Also looks like haproxy added support for service discovery https://www.haproxy.com/blog/dns-service-discovery-haproxy/

**Comment by gyliu513** [comment]
There is a keepalived cloud provider can also provide loadbalancer type for services https://github.com/munnerz/keepalived-cloud-provider

**Comment by bputt** [comment]
@gyliu513 thanks, and does k8s support multiple cloud providers? The keepalived-cloud-provider docs say I should use ```--cloud-provider=external```, but I have it set to ```--cloud-provider=openstack``` for provisioning volumes

**Comment by gyliu513** [comment]
Not sure about this, perhaps you can ask in dev list for help @bputt

**Comment by gyliu513** [comment]
I have a keepalived chart for loadbalancer at https://github.com/gyliu513/work/tree/master/k8s/charts/keepalived
