### ISSUE TITLE
kubefed init errors if namespace already exists

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#19]
<a href="https://github.com/derekwaynecarr"><img src="https://avatars3.githubusercontent.com/u/6233452?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [derekwaynecarr](https://github.com/derekwaynecarr)**
_Thursday Jun 08, 2017 at 06:04 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/47159_

----

**Is this a BUG REPORT or FEATURE REQUEST?**
BUG

**What happened**:

```
$ kubectl create ns federation-system
$ kubefed init my-fed --dns-provider=google-clouddns \
        --federation-system-namespace="federation-system" \
        --etcd-persistent-storage=false
Error from server (AlreadyExists): namespaces "federation-system" already exists
```

**What you expected to happen**:
I expected the command to not error if the namespace already existed.
kubefed should only create a namespace if it doesnt already exist, otherwise just use the one i gave.

**How to reproduce it** (as minimally and precisely as possible):
see above

**Anything else we need to know**:
nope

**Comment by irfanurrehman** [comment]
<a href="https://github.com/derekwaynecarr"><img src="https://avatars3.githubusercontent.com/u/6233452?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [derekwaynecarr](https://github.com/derekwaynecarr)**
_Thursday Jun 08, 2017 at 06:05 GMT_

----

cc @marun @kubernetes/sig-federation-bugs

**Comment by irfanurrehman** [comment]
<a href="https://github.com/k8s-merge-robot"><img src="https://avatars0.githubusercontent.com/u/13653959?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k8s-merge-robot](https://github.com/k8s-merge-robot)**
_Thursday Jun 08, 2017 at 06:05 GMT_

----

@derekwaynecarr There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br>(1) mentioning a sig: `@kubernetes/sig-<team-name>-misc`<br>(2) specifying the label manually: `/sig <label>`<br><br>_Note: method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels)_

**Comment by irfanurrehman** [comment]
<a href="https://github.com/marun"><img src="https://avatars3.githubusercontent.com/u/451477?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marun](https://github.com/marun)**
_Monday Jun 12, 2017 at 21:49 GMT_

----

@madhusudancs Should this be blocking 1.7?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Monday Jun 12, 2017 at 22:02 GMT_

----

@marun No, I don't think it should.  Bumping to v1.8.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/walteraa"><img src="https://avatars1.githubusercontent.com/u/5852041?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [walteraa](https://github.com/walteraa)**
_Monday Jul 24, 2017 at 13:28 GMT_

----

The same happens when trying to join in a federation. There are some RBAC(e.g.: `serviceaccount` and `clusterrolebinding`) which are happening the same issue. Should the `kubefed join` command rollback/clean-up all changes when isn't possible to join in a federation?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/walteraa"><img src="https://avatars1.githubusercontent.com/u/5852041?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [walteraa](https://github.com/walteraa)**
_Monday Jul 24, 2017 at 20:38 GMT_

----

Thanks @madhusudancs

**Comment by irfanurrehman** [comment]
<a href="https://github.com/k8s-merge-robot"><img src="https://avatars0.githubusercontent.com/u/13653959?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k8s-merge-robot](https://github.com/k8s-merge-robot)**
_Saturday Sep 09, 2017 at 08:06 GMT_

----

[MILESTONENOTIFIER] Milestone Removed

@derekwaynecarr

**Important**:
This issue was missing labels required for the v1.8 milestone for more than 7 days:

_**priority**_: Must specify exactly one of [`priority/critical-urgent`, `priority/important-longterm`, `priority/important-soon`].

Removing it from the milestone.

<details>
Additional instructions available <a href="https://github.com/kubernetes/community/blob/master/contributors/devel/release/issues.md">here</a>
The commands available for adding these labels are documented <a href="https://github.com/kubernetes/test-infra/blob/master/commands.md">here</a>
</details>

**Comment by irfanurrehman** [comment]
cc @derekwaynecarr

**Comment by davidstack** [comment]
the reason i want to use the default namespace is here[ Ceph StorageClass](https://github.com/kubernetes/examples/blob/master/staging/persistent-volume-provisioning/README.md), where i want use ceph rbd as the backend of etcd, but the ceph rbd need a ceph-secret must exist at the namespace.
the kubefed allow use exist namespace

**Comment by prakashsingh08** [comment]
Hi @davidstack 
is this issue resolved?

**Comment by davidstack** [comment]
@prakashsingh08 no, i change to use "manual" storage class

**Comment by prakashsingh08** [comment]
Hi @davidstack ,
is this possible to give some steps to avoid this issue?

**Comment by davidstack** [comment]
1.create a pv useing manaul storage class

> kind: PersistentVolume
apiVersion: v1
metadata:
  name: fed-etcd1
  namespace: federation-system
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/fed-etcd/"
2. kubefed init useing this command:

> kubefed init  fed-cluster --host-cluster-context=admin-cluster.local  --dns-provider="coredns" --dns-zone-name="fed.iop.com." --dns-provider-config="coredns-provider.conf" --image='registry.cluster1.com:5000/library/iop/quay.io/coreos/hyperkube:v1.8.2_coreos.0'  --api-server-service-type=NodePort --**etcd-persistent-storage=true --etcd-pv-capacity='5Gi' --etcd-pv-storage-class=manual**  --etcd-image='registry.cluster1.com:5000/library/iop/quay.io/coreos/etcd:v3.2.4'   --apiserver-arg-overrides="--runtime-config=federation/v1beta1=true"
