### ISSUE TITLE
Missing information in docs about jobs API

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#198]
Jobs API in federation apiserver is not enabled by default and needs to be explicitly enabled (for example using `--runtime-config=api/all=true` while starting the federation apiserver). This information does not reflect correctly in current documentation about jobs [here](https://kubernetes.io/docs/tasks/administer-federation/job/).
This should be updated.

**Comment by vaibhavsingh97** [comment]
@irfanurrehman I am beginner and I want to take up this issue.

**Comment by irfanurrehman** [comment]
Welcome @vaibhavsingh97. Please go ahead and don't hesitate to ask for information.
