### ISSUE TITLE
Federation does not resolve Hostname, need to use IP

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#199]
<a href="https://github.com/tommyknows"><img src="https://avatars2.githubusercontent.com/u/16387735?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tommyknows](https://github.com/tommyknows)**
_Thursday Dec 21, 2017 at 08:33 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/57505_

----

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When adding a cluster to the federation (with `kubefed join`) the "server" field (in kubeconfig) needs to be an IP-Adress. If I use "server: https://hostname:6443", the cluster will be offline when executing `kubectl get clusters` due to `Cluster is not reachable`

**What you expected to happen**:
I expect the federation to be able to work with hostnames as well - as it works with kubectl too. Or at least, it should be documented somewhere that you need to use IP-Addresses.

**How to reproduce it (as minimally and precisely as possible)**:
Create a federation cluster and trying to add a cluster that uses hostnames instead of IPs.

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.5
- Cloud provider or hardware configuration: On-Premise / OpenStack
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`): 4.4.0

**Comment by irfanurrehman** [comment]
<a href="https://github.com/tommyknows"><img src="https://avatars2.githubusercontent.com/u/16387735?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tommyknows](https://github.com/tommyknows)**
_Thursday Dec 21, 2017 at 08:52 GMT_

----

@kubernetes/sig-multicluster-bugs

**Comment by irfanurrehman** [comment]
<a href="https://github.com/k8s-ci-robot"><img src="https://avatars0.githubusercontent.com/u/20407524?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k8s-ci-robot](https://github.com/k8s-ci-robot)**
_Thursday Dec 21, 2017 at 08:52 GMT_

----

@tommyknows: Reiterating the mentions to trigger a notification: 
@kubernetes/sig-multicluster-bugs


<details>

In response to [this](https://github.com/kubernetes/kubernetes/issues/57505#issuecomment-353294065):

>@kubernetes/sig-multicluster-bugs


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by irfanurrehman** [comment]
cc @tommyknows

**Comment by tommyknows** [comment]
I think this is still a valid issue and should be at least documented somewhere (if it's not "fixed").
Correct me if I should be wrong :-)

/remove-lifecycle stale

**Comment by quinton-hoole** [comment]
SGTM
