### ISSUE TITLE
federation API not in client-go

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#206]
<a href="https://github.com/justinsb"><img src="https://avatars2.githubusercontent.com/u/100893?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [justinsb](https://github.com/justinsb)**
_Sunday Feb 12, 2017 at 20:27 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/41302_

----

The federation objects are not currently in client-go.  I believe this makes it hard/impossible to use federation with client-go.  The challenges I hit:

* you would have to refer to the main kubernetes/kuberentes repo again for the federation objects
* mixing and matching the federation objects from kubernetes/kubernetes is tricky, because for example ClusterSpec has a SecretRef field which is of type `k8s.io/kubernetes/pkg/api/v1.LocalObjectReference`, but in client-go view that is `k8s.io/client-go/pkg/api/v1...` which is different.

I think we need to include the federation objects into client-go.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/liggitt"><img src="https://avatars0.githubusercontent.com/u/980082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [liggitt](https://github.com/liggitt)**
_Monday Feb 13, 2017 at 04:21 GMT_

----

cc @kubernetes/sig-api-machinery-misc @kubernetes/sig-federation-feature-requests

**Comment by irfanurrehman** [comment]
<a href="https://github.com/sttts"><img src="https://avatars0.githubusercontent.com/u/730123?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sttts](https://github.com/sttts)**
_Monday Feb 13, 2017 at 07:37 GMT_

----

We could blindly copy federation types into client-go as well. But I would very much prefer to start thinking about making client-go more composable to avoid that it becomes our new monolith repo. /cc @deads2k

**Comment by irfanurrehman** [comment]
<a href="https://github.com/deads2k"><img src="https://avatars0.githubusercontent.com/u/8225098?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [deads2k](https://github.com/deads2k)**
_Monday Feb 13, 2017 at 13:17 GMT_

----

> We could blindly copy federation types into client-go as well. But I would very much prefer to start thinking about making client-go more composable to avoid that it becomes our new monolith repo. /cc @deads2k

I agree.  We need to think about how different client-go APIs interact and build on top of each other instead of simply producing a copy/paste which can never be extended.  As we get more aggregated API servers like service-catalog and (hopefully) podinjectionpolicy, this becomes even more obvious.

@lavalamp @caesarxuchao

**Comment by irfanurrehman** [comment]
<a href="https://github.com/lavalamp"><img src="https://avatars0.githubusercontent.com/u/647318?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lavalamp](https://github.com/lavalamp)**
_Monday Feb 13, 2017 at 23:23 GMT_

----

client-go should not be a grab bag for clients for all APIs. The long term plan here is to have a two-layer client structure.

* client-core contains things like RESTClient, discovery client, dynamic client, transport, informers, etc.
* client-go contains the API types and generated code

Other projects (like federation) can host their own version of the latter.

Additionally I'd like to get to a point where we can generate a client specifically for a user, given their cluster's OpenAPI spec.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/caesarxuchao"><img src="https://avatars2.githubusercontent.com/u/2823529?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [caesarxuchao](https://github.com/caesarxuchao)**
_Tuesday Feb 14, 2017 at 04:22 GMT_

----

I agree with @lavalamp's vision.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/k8s-merge-robot"><img src="https://avatars0.githubusercontent.com/u/13653959?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k8s-merge-robot](https://github.com/k8s-merge-robot)**
_Wednesday May 31, 2017 at 22:54 GMT_

----

@justinsb There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br>(1) mentioning a sig: `@kubernetes/sig-<team-name>-misc`<br>(2) specifying the label manually: `/sig <label>`<br><br>_Note: method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md)._

**Comment by irfanurrehman** [comment]
<a href="https://github.com/fejta-bot"><img src="https://avatars1.githubusercontent.com/u/30488982?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fejta-bot](https://github.com/fejta-bot)**
_Monday Jan 08, 2018 at 18:26 GMT_

----

Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

Prevent issues from auto-closing with an `/lifecycle frozen` comment.

If this issue is safe to close now please do so with `/close`.

Send feedback to sig-testing, kubernetes/test-infra and/or `@fejta`.
/lifecycle stale

**Comment by irfanurrehman** [comment]
cc @justinsb

**Comment by sttts** [comment]
@shashidharatd I don't think this is technical dept, at least not with the issue description above. Federation types will probably never be in client-go. Merely, federation has to provide a client-go library (compare https://github.com/openshift/client-go).

**Comment by shashidharatd** [comment]
Agree @sttts, the heading is not apt now. We should have client-go for federation which extends the k8s.io/client-go as opined above. Thanks for the above tip, i will study it.
