### ISSUE TITLE
Federation dependencies should not be managed by glide

### ISSUE THREAD

**Issue by xtophs** [kubernetes/federation#220]
Azure SDK dependencies in `vendor/GitHub.com/Azure/azure-sdk-for-go` imported the entire SDK instead of only importing dependent files like it's done in kubernetes/kubernetes.

As @quinton-hoole points out

> Based on the following issue, that seems like the wrong direction.  As far as I understand, kubernetes/kubernetes decided to stick with godeps until "go dep" is usable, and not, ever, use glide.
> 
> https://github.com/kubernetes/kubernetes/issues/44873
> 

Dependencies should be managed with `godeps` or `go dep`

**Comment by quinton-hoole** [comment]
Some more context.  Also, this applies to all dependencies, so I'll edit the subject accordingly.

It looks like @marun used glide, not godeps for vendoring in the new kubernetes/federation repo:

https://github.com/kubernetes/federation/pull/112

Based on the following issue, that seems like the wrong direction.  As far as I understand, kubernetes/kubernetes decided to stick with godeps until "go dep" is usable, and not, ever, use glide.

https://github.com/kubernetes/kubernetes/issues/44873

The attempts to make "go deps" work seem to be centered here:

https://github.com/kubernetes/kubernetes/pull/57795

Assuming that the above is true, we should switch back from glide to godeps, or, more adventurously, "go deps".  Maru?

**Comment by marun** [comment]
As per [the discussion](https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/LdWSBk2FVUc) on the mailing list, it is not desirable to switch to godeps.  Switching to dep is blocked on k/k and client-go publishing ``Gopkg.toml``.  In the meantime, culling unused vendored code can be accomplished via the [prune script](https://github.com/kubernetes/federation/blob/master/hack/prune-deps.sh).
