### ISSUE TITLE
Version mismatch between vendored libraries in vendor/k8s.io/kubernetes and vendor/github.com/azure

### ISSUE THREAD

**Issue by xtophs** [kubernetes/federation#221]
The versions of vendor/github.comAzure/azure-sdk-for-go do not match what's required by vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure.

Error on build is:
```
# make
[...]
# k8s.io/federation/vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure.go:170:4: cannot use *oauthConfig (type adal.OAuthConfig) as type string in argument to adal.NewServicePrincipalTokenFromMSI
```

This will be fixed with PR #219

**Comment by irfanurrehman** [comment]
@xtophs are you doing this on your own branch??
I don't see the error you specified on latest master (or any earlier version either). 
As far as I understand the azure packages vendored  in correctly map to the version used by the k8s vendored in (commit hash `4aee60804874a7cd2533425ac81bc9ecbda5a38b`).

**Comment by xtophs** [comment]
Yes, I did this in my branch. The files in vendor/github.com/Azure seem to be from HEAD at the time of the split. vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure depends on azure-sdk-for-go v10.0.4-beta-1-g786cc84 and go-autorest depends on v8.0.0.

PR #219 has the correct versions of these libraries.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
