### ISSUE TITLE
Upgrade Instructions

### ISSUE THREAD

**Issue by fkorotkov** [kubernetes/federation#225]
Hello there,

I configured a federation cluster using version 1.8.5 a few months back. I've just upgraded my GKE cluster to version 1.9.2 of k8s and I was wondering how to upgrade `controller-manager` and `apiserver`. It doesn't seem to be that straightforward and I haven't found an instruction beside [`deploy/cluster/upgrade.sh` script](https://github.com/kubernetes/federation/blob/master/deploy/cluster/upgrade.sh) which suggests just to bump version of `gcr.io/google_containers/fcp-amd64` image for both `controller-manager` and `apiserver` deployments.

The confusing part to me here is that `gcr.io/google_containers/fcp-amd64` is not on `gcr.io` and according to `federation-up.sh` I should [push it myself](https://github.com/kubernetes/federation/blob/546b9812a76dd70cf45c48db85c4a343a87ab6f9/deploy/cluster/federation-up.sh#L139-L152).

I would really appreciate if someone with better understanding will confirm my guesses about the upgrade process.

**Comment by irfanurrehman** [comment]
@fkorotkov The current mechanism of upgrading the control plane is really as simple as upgrading the image. You can build the image here and push it to your own registry or wait for a few days as listed in https://github.com/kubernetes/federation/issues/227#issuecomment-364994287.

**Comment by fkorotkov** [comment]
Thanks @irabinovitch! I'll wait. Nothing seems to be broken 👌
