### ISSUE TITLE
Getting kubefed instructions are not obsolete

### ISSUE THREAD

**Issue by fkorotkov** [kubernetes/federation#226]
Hello there,

According to k8s federation documentation here: https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/#getting-kubefed

In order to install `kubefed` one should run:

```
# OS X
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/kubernetes-client-darwin-amd64.tar.gz
tar -xzvf kubernetes-client-darwin-amd64.tar.gz
```

Right now the stable version is `1.9.3` and `kubernetes-client-darwin-amd64.tar.gz` for this version doesn't contain `kubefed` executable.

**Comment by irfanurrehman** [comment]
@fkorotkov, Please wait for few days and we should be able to provide you with the federation binary and image matching 1.9.x clusters. In the interim you should be able to build the same from this repo. Also read https://github.com/kubernetes/federation/issues/227#issuecomment-364994287.

**Comment by irfanurrehman** [comment]
@fkorotkov 
Release published [here](https://github.com/kubernetes/federation/releases/tag/v1.9.0-alpha.3)

**Comment by irfanurrehman** [comment]
Getting kubefed instructions updated as per https://github.com/kubernetes/website/pull/7429.
/close
