### ISSUE TITLE
batch/v1beta1 for 1.9.x?

### ISSUE THREAD

**Issue by mastamark** [kubernetes/federation#228]
I'm curious if we plan to bring batch/v1beta1 into the federation api.

I see this here:  https://github.com/kubernetes/federation/commit/606e2c57e4866bf987221f7677a8ae0e6c749488#diff-a1329dbefeeb924bbbadaa79a76e4ae3R1251 which does indeed seem to identify that there was issues with bringing it in.

I'm essentially looking for this bad boy right here:  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#cronjob-v1beta1-batch

My federated endpoint (fcp built from master) shows the following even with the api server flag (--apiserver-arg-overrides="--runtime-config=api/all=true") to handed along to kubefed:
* autoscaling/v1
* batch/v1
* extensions/v1beta1
* federation/v1beta1
* v1

**Comment by irfanurrehman** [comment]
@mastamark, we do not have any immediate plans of federating the batch api, but we can certainly consider it. If you have a compelling use case for the same and the community needs it, it will certainly help getting it up in priority. Please let us know about your use case!

**Comment by mastamark** [comment]
It's more of a flow/context switching/usability thing.  Devs/Operators/K8-ers looking to deploy services on a given new cluster can create deployments, services, etc. directly against the federated api including with placement policies or federated deployment preferences, but to do the CronJob they have to switch context and apply directly against a single cluster in the federation.  For that single type of job.

In a perfect world they would be able to apply _all_ against the federated api and set a constraint for that single cluster.

That being said, it's not an incredible hardship.  Also I suspect it's a bit of an unreasonable ask to assume that EVERY cluster api feature will have parity in the federated api so I'm good knowing that it's just not in the roadmap and can make plans accordingly.

Thank you!
