### ISSUE TITLE
kubefed hang on kubeadm cluster in AWS

### ISSUE THREAD

**Issue by mengesb** [kubernetes/federation#234]
I've explored a number of kubernetes documents on stack and here in the various repos, and much of the documents. The Issue i'm experiencing is most similar to #101 however I'm deploying to a kubeadm generated cluster on AWS. While I know that kubeadm's target isn't AWS this is where we have deployed as a demo location. I'm trying to initalize a federation and I do have aws route53 zones i could be using however it seems to get stuck similar to https://github.com/kubernetes/kubernetes/issues/39271 - where an init seems to wait forever. When we inspected the federation service api ; it was waiting on external IP, which I'm not sure where it would need to go from there.

**Comment by irfanurrehman** [comment]
@mengesb apologies for a delayed response.
It seems you are trying init with default params in which case a service type `LoadBalancer` is created (Which seems not feasible in your setup). You should ideally try `kubefed init` with option `--api-server-service-type='NodePort'`. Please be aware that for this to work your cluster nodes should have reachable IPs from the client node you are trying `kubefed init`
