### ISSUE TITLE
Feature Ask: OpenStack Designate DNS Provider

### ISSUE THREAD

**Issue by grahamhayes** [kubernetes/federation#236]
As of 1.9.x only AWS, CoreDNS, and Google Cloud DNS are supported as DNS providers for federation.

There is work underway to add Azure [#130 / #219].

The ask is to implement a DNS provider for the DNS project in OpenStack (Designate).

**Comment by GabrielSVinha** [comment]
@grahamhayes I am interested in helping with this issue. I'm planning on a docs/sketch for the changes soon.
