### ISSUE TITLE
Add option to setup kubeconfig for existing fcp

### ISSUE THREAD

**Issue by chrisprobst** [kubernetes/federation#238]
When there is an existing fcp running, there should be an option to setup kubeconfig accordingly.
For instance: A new user working on the federated cluster has no context "kfed".

There is no way of setting the config up for this user without copy-paste an exsting .kube/config.
Not to speak of what happens when there is no existing .kube/config anymore (good luck, federation must be recreated...).

So there should be an option to kube setup-config-for-existing --context... 

Maybe I missed something, but I think this is a severe issue because you could easily lose the .kube/config.

**Comment by irfanurrehman** [comment]
@chrisprobst apologies for a delayed reply. Somehow missed the issue. 
There are two parts in the issue that you have reported:
1 - You have setup fcp and now wants to share the same with another user (the fcp context for example `my-federation` is created in the default kubeconfig or in something that you can explicitly provide).

For this you can actually provide an alternative kubeconfig using `--kubeconfig` and your federation context for example `my-federation` and relevant info (auth info, cluster endpoint, etc) will be stored in this kubeconfig. You can use this config to share with another user. The command however uses the same config to search for the base cluster context also. Its quite overbearing to provide separate kubeconfig options  for the base cluster and the federation context.

2 - You lost/deleted your kubeconfig.

This is like loosing your username/token/auth info, which is not stored anywhere else. This information could be linked to the user and stored into some secure servers, in case a cloud provider/service provider chooses to provide this as a managed solution. This is also similar to setting up a kubernetes cluster with secure access and then loose your kubeconfig. You can setup the kubeconfig again, only if you have access to the master node and know where does cluster store the needed certificates, and also know how to create the credential entries in kubeconfig using these certificates. Ideally you should be able to do the same in case of federation also by accessing the certificates from the federation-apiserver pod (if you have access to the same).
