### ISSUE TITLE
Build kubefed binary for Mac

### ISSUE THREAD

**Issue by fkorotkov** [kubernetes/federation#240]
It will be nice to have binaries of `kubefed` prebuilt for Mac OS. Right now GitHub release page has only links for linux binaries:

https://storage.cloud.google.com/kubernetes-federation-release/release/v1.9.0-alpha.3/federation-client-linux-amd64.tar.gz

It will be nice to have `federation-client-darwin-amd64.tar.gz` binaries as well.

PS maybe even binaries for Windows?

**Comment by smaslennikov** [comment]
I'm in the same boat, though this seems to have been fixed here https://github.com/kubernetes/website/pull/2899/files and some discussion is here: https://github.com/kubernetes/website/issues/2909
