### ISSUE TITLE
GKE Federation - Cross Cluster Service Discovery with GoogleDNS in one VPC

### ISSUE THREAD

**Issue by marekaf** [kubernetes/federation#274]
Hi,
I'm trying to setup a working demo on GCP.
2 GKE clusters, each in different region, say 
- southamerica-east1-b cluster-BR
- europe-west1-d cluster-EU
I want a service A running in cluster-BR to be able to communicate via standard local dns svc discovery with service B running in cluster-EU in one Google VPC. 

service A has one pod in cluster-BR, other pod in cluster-EU
service B (10.23.243.18) has only one pod (IP 10.5.6.3), in cluster-EU

**What I want to achieve:**
service A in cluster-BR wants to communicate with service B, it queries a local dns service-b.default.federation, kube-dns find out there are no healthy endpoints of service-b in cluster-BR so it checks GoogleDNS (managed by federation api plane) and returns a private IP 10.23.243.18 which is the IP or service-b k8s service running in cluster-EU. 

**Why is this not working?**
I'm able to communicate from one pod in cluster-EU with pods in cluster-BR using their local pod IPs.
I'm not able to hit services' IPs (virtual IPs?, I can't see them from the outside?). Does not matter if it's ClusterIP or NodePort. I don't want to use External Loadbalancers. Internal loadbalancer are regional, so I can't use those either.
GoogleDNS with federation handles public ipv4 only from LoadBalancer service specs, it ignores everything else. 

Am I the only one trying to solve this problem? What am I missing? 

Thanks :)

**Comment by relvan1** [comment]
Any Solution for this?

**Comment by relvan1** [comment]
@bartimar thanks dude. I will take a look on istio

**Comment by gmflau** [comment]
I followed this Istio setup (https://istio.io/docs/examples/multicluster/gke/).  Looks like pod communications between 2 GKE clusters over DNS is through a Load Balancer.  What I wanted to do is to use DNS to lookup a pod in one GKE cluster from a pod in another GKE cluster.  I wanted to exactly pinpoint a DNS service name such as opscenter-0.opscenter.default.svc.cluster.local where opscenter itself is a statefulset.  Not sure if Istio is solving this kind of use case.

**Comment by saamalik** [comment]
The Federation documentation clearly states this should be a supported use-case, but I'm also facing the same issue. 

Docs: [Cross-cluster Service Discovery using Federated Services](https://kubernetes.io/docs/tasks/federation/federation-service-discovery/)
Check section _From pods inside your federated clusters_. 

Did anyone find any other workarounds, short of using istio?

**Comment by gmflau** [comment]
I would want to pursue a solution using Istio since the K8 Federation project is not promising.

**Comment by bartimar** [comment]
> I followed this Istio setup (https://istio.io/docs/examples/multicluster/gke/). Looks like pod communications between 2 GKE clusters over DNS is through a Load Balancer. 

Yep, all traffic is going through the istio-ingressgateway which is a LoadBalancer svc type. Which means all the traffic is always going through the one cluster's ingressgateway. Maybe having more istio masters would help?

**Comment by saamalik** [comment]
Got cross-cluster service discovery working with Google CloudDNS. There was a swallwed exception deep-inside `kube-dns`:  _kube-system/kube-dns_ service account is missing VIEW permissions to list _nodes_. Run the following command and _make_ sure the service is _LoadBalancer_ type:

    kubectl create clusterrolebinding nodes-kube-dns --clusterrole=system:node --serviceaccount kube-system:kube-dns

Good luck!

**Comment by marekaf** [comment]
any progress on this?

**Comment by quinton-hoole** [comment]
@marekaf I would suggest asking in the SIG-Multicluster Slack channel 
 ( https://kubernetes.slack.com/messages/C09R1PJR3 ) or mailing list https://groups.google.com/forum/#!forum/kubernetes-sig-multicluster . 

Or file an issue in https://github.com/kubernetes-sigs/federation-v2

I'm not sure why this repo is still accepting updates, and not being redirected to the above one.  I'll try to have that fixed.

**Comment by quinton-hoole** [comment]
@marekaf Also, did https://github.com/kubernetes/federation/issues/274#issuecomment-430120387 not work for you?
