### ISSUE TITLE
Kubefed get and describe giving inconsistent data

### ISSUE THREAD

**Issue by jazzyarchitects** [kubernetes/federation#276]
` kubectl get clusters ` returns ` No resource found. Error from server (NotAcceptable): unknown (get clusters.federation) `
while
` kubectl describe clusters ` returns the description of all the joined clusters. 

Possible bug in implementation? 

Attaching screenshot
<img width="843" alt="screen shot 2018-07-04 at 1 58 51 am" src="https://user-images.githubusercontent.com/11012686/42243332-9867dc90-7f2e-11e8-8ce8-5630a6493e5a.png">

**Comment by mastamark** [comment]
I observed this using kubectl version 1.11.x against a federation that was 1.9.x.  Changing the snap channel to 1.9.x or 1.10.x "solved" it for me.  (`sudo snap switch --channel=1.10/stable kubectl` or `sudo snap switch --channel=1.9/stable kubectl`)

**Comment by jazzyarchitects** [comment]
Thanks. Works now
