### ISSUE TITLE
Where can I see the release plan

### ISSUE THREAD

**Issue by zqdlove** [kubernetes/federation#277]
Hello，Where can I see the release plan，When to support the new version K8S 1.10.*

**Comment by smaslennikov** [comment]
https://github.com/kubernetes/federation/commit/8a15454fde26f63c18d455a64ed0e13cd48fadfa fixed that, but the latest release doesn't include that (yet). I just cloned down the repo and built it from there.

**Comment by zqdlove** [comment]
I mean federation support kubernetes 1.10.x clusters,thank you.
