### ISSUE TITLE
invalid apiserver image name (broken versioning)

### ISSUE THREAD

**Issue by yutongp** [kubernetes/federation#281]
I built the project `master` branch(ccbc47b7f65e09a4bfbc27e157120e0396156d67) with `make` on MacOS.
I got these output when I run `kubefed version`:
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.1", GitCommit:"ee18aa41359293b5c9c7e13a35697690491736c9", GitTreeState:"clean", BuildDate:"2018-08-08T18:09:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
the `GitVersion` and `GitCommit` version is broken. This issue caused `kubefed` try to fetch wrong `apiserver` image after I ran `kubefed init` for my GCP clusters.
On GCP console I saw this error message:
```
Failed to apply default image tag "gcr.io/k8s-jkns-e2e-gce-federation/fcp-amd64:v0.0.0-master_$Format:%h$": couldn't parse image reference "gcr.io/k8s-jkns-e2e-gce-federation/fcp-amd64:v0.0.0-master_$Format:%h$": invalid reference format: InvalidImageName
```

P.S. I built the binrary from master branch because I want to use `credentials-kubeconfig` to avoid #110

**Comment by yutongp** [comment]
I tried to modify `federation/pkg/version/version.go` to hard code a version, but it didn't change the output of `kudefed version`. Then I tried to hard hard code  `vendor/k8s.io/kubernetes/pkg/version/version.go`, and that changed the output of `kudefed version`.

This sounds like a bug, right? shouldn't `kubefed` takes the output of ``federation/pkg/version/` instead of `vendor/k8s.io/kubernetes/pkg/version`?

**Comment by yutongp** [comment]
after hard code the version, I was able to pull `apiserver` image, but the version on server is still incorrect:
```
kubectl --context=kfed version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Now I don't have right API support on server:
```
kubectl --context=kfed api-versions
extensions/v1beta1
federation/v1beta1
v1
```
```
kubectl --context=kfed create deployment nginx --image=nginx && \
 kubectl --context=kfed scale deployment nginx --replicas=4
WARNING: New generator "deployment-basic/apps.v1" specified, but it isn't available. Falling back to "deployment-basic/v1beta1".
error: no matches for kind "Deployment" in version "apps/v1"
```

**Comment by cap1981** [comment]
same issue
```
About to download some binaries. This might take a while...
# destination:
#   /root/federation-v2/bin
# versions:
#   etcd:           etcd Version: 3.3.0+git
#   kube-apiserver: Kubernetes v0.0.0-master+$Format:%h$
#   kubectl:        Client Version: v0.0.0-master+$Format:%h$
#   kubebuilder:    2018/09/24 19:08:53 kubebuilder must be run from the project root under $GOPATH/src/<package>. 
Current GOPATH=/root/go.  
Current directory=/root/federation-v2
Error downloading assets

```

**Comment by chiraggupta06** [comment]
> same issue
> 
> ```
> About to download some binaries. This might take a while...
> # destination:
> #   /root/federation-v2/bin
> # versions:
> #   etcd:           etcd Version: 3.3.0+git
> #   kube-apiserver: Kubernetes v0.0.0-master+$Format:%h$
> #   kubectl:        Client Version: v0.0.0-master+$Format:%h$
> #   kubebuilder:    2018/09/24 19:08:53 kubebuilder must be run from the project root under $GOPATH/src/<package>. 
> Current GOPATH=/root/go.  
> Current directory=/root/federation-v2
> Error downloading assets
> ```

@cap1981 hi Chirag, could you please tell me whether the issue was resolved and if yes, then how?

Thanks in advance.

Regards,
Chirag Gupta
