### ISSUE TITLE
Unable to pull Federation v1 Docker images

### ISSUE THREAD

**Issue by red5bongo** [kubernetes/federation#294]
The project that hosts the docker images is denying access when kubefed tries to pull down the images for API server and Controller Manager:

Events:
  Type     Reason                 Age              From                                       Message
  ----     ------                 ----             ----                                       -------
  Normal   Scheduled              2m               default-scheduler                          Successfully assigned controller-manager-58ddbc4488-66gzd to gke-trident-new-np-1158f0f4-gpw1
  Normal   SuccessfulMountVolume  2m               kubelet, gke-trident-new-np-1158f0f4-gpw1  MountVolume.SetUp succeeded for volume "controller-manager-kubeconfig"
  Normal   SuccessfulMountVolume  2m               kubelet, gke-trident-new-np-1158f0f4-gpw1  MountVolume.SetUp succeeded for volume "federation-controller-manager-token-w5np8"
  Normal   SandboxChanged         2m (x2 over 2m)  kubelet, gke-trident-new-np-1158f0f4-gpw1  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling                2m (x3 over 2m)  kubelet, gke-trident-new-np-1158f0f4-gpw1  pulling image "gcr.io/k8s-jkns-e2e-gce-federation/fcp-amd64:v1.10.0-alpha.0"
  Warning  Failed                 2m (x3 over 2m)  kubelet, gke-trident-new-np-1158f0f4-gpw1  Failed to pull image "gcr.io/k8s-jkns-e2e-gce-federation/fcp-amd64:v1.10.0-alpha.0": rpc error: code = U
nknown desc = Error response from daemon: Get https://gcr.io/v2/k8s-jkns-e2e-gce-federation/fcp-amd64/manifests/v1.10.0-alpha.0: denied: Token exchange failed for project 'k8s-jkns-e2e-gce-federatio
n'. Please enable or contact project owners to enable the Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?projec
t=k8s-jkns-e2e-gce-federation before performing this operation.
  Warning  Failed                 2m (x3 over 2m)  kubelet, gke-trident-new-np-1158f0f4-gpw1  Error: ErrImagePull
  Normal   BackOff                1m (x6 over 2m)  kubelet, gke-trident-new-np-1158f0f4-gpw1  Back-off pulling image "gcr.io/k8s-jkns-e2e-gce-federation/fcp-amd64:v1.10.0-alpha.0"
  Warning  Failed                 1m (x6 over 2m)  kubelet, gke-trident-new-np-1158f0f4-gpw1  Error: ImagePullBackOff

I'm unable to pull it from a standalone Docker install as well.  This is happening for 1.9.0-alpha2, 3 and 1.10.0-alpha0.

**Comment by acloudiator** [comment]
Same issue for `gcr.io/k8s-jkns-e2e-gce-federation/fcp-amd64:v1.9.0-alpha.3`. 
Shouldn't it be public without authentication?

**Comment by hellolijj** [comment]
i also meet this problem = =

**Comment by acloudiator** [comment]
I think `K8S Federation v1` community support might have been stopped. The focus would be on  [K8S Federation v2](https://github.com/kubernetes-sigs/federation-v2).
