### ISSUE TITLE
Intent to archive this repo as read-only

### ISSUE THREAD

**Issue by fejta** [kubernetes/federation#300]
https://github.com/kubernetes/federation/issues/298 has gone unresolved for more than a quarter, and there does not appear to be activity on this repo: no issues, no PRs.

I plan to mark this repo as archived next week. If we need to continue making changes to this repo, please someone step up and create the security contacts file. Thanks!

/assign @nikhiljindal @csbell @madhusudancs

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-multicluster-proposals @kubernetes/sig-multicluster-pr-reviews 
@shashidharatd @irfanurrehman @marun

**Comment by shashidharatd** [comment]
SGTM. the federation repo is not maintained and users and developers are encouraged to look at [federation-v2](https://github.com/kubernetes-sigs/federation-v2)

**Comment by fejta** [comment]
Archiving now...
