### ISSUE TITLE
Enable coredns etcd secure mode

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#32]
<a href="https://github.com/gyliu513"><img src="https://avatars1.githubusercontent.com/u/4461983?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gyliu513](https://github.com/gyliu513)**
_Wednesday Aug 16, 2017 at 09:41 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/50761_

----

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
The kubernetes federation has a provider of coreos, we cannot enable secure mode for etcd, it is better support secure mode for etcd.

```
[root@cfc-555 federation]# cat coredns-provider.conf
[Global]
etcd-endpoints = http://etcd-cluster.default:2379 
zones = example.com.
coredns-endpoints = coredns-coredns:53
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig federation

/cc @kubernetes/sig-federation-feature-requests

**Comment by irfanurrehman** [comment]
<a href="https://github.com/gyliu513"><img src="https://avatars1.githubusercontent.com/u/4461983?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gyliu513](https://github.com/gyliu513)**
_Wednesday Aug 16, 2017 at 09:45 GMT_

----

/cc @liqlin2015

**Comment by irfanurrehman** [comment]
cc @gyliu513

**Comment by shashidharatd** [comment]
This is addressed by https://github.com/kubernetes/kubernetes/pull/47049
/close
