### ISSUE TITLE
Proposal: Service connection affinity

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#36]
<a href="https://github.com/eliaslevy"><img src="https://avatars1.githubusercontent.com/u/725218?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eliaslevy](https://github.com/eliaslevy)**
_Wednesday Oct 14, 2015 at 23:34 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/15675_

----

As of now connections to Services are either handled in a round robin fashion (the default) or can make use of client IP based affinity, where the endpoint for the initial connection to the service by a client is selected in a round robin fashion and subsequent connections will attempt to use the previously selected endpoint.

In some environments there is a need for a topographical or administrative prioritization of the Service endpoint selection.  For instance, a cluster may be comprised of multiple zones with Service endpoints spread across zones.  Latencies across zones may be low, yet still higher than intra-zone latencies.  There may also be financial costs associated to inter-zone traffic.  Thus, it is could be desirable for a number of reasons to prioritize endpoints for a Service within the same zone as that of Pods making connections to the Service.

Note that this proposal is distinct from that of #14484. #14484 proposes priority affinity when scheduling Pods (colocation).  I am proposing priority affinity of network connections to Services.

This could be implemented allowing the admin to specify a tag selector within the session affinity spec.  kube-proxy could then look up the tag on the Pod that initiated a connection and on any Pods that are endpoints for the Service.  It would prioritize endpoint Pods that a tag with a value that matches the value of the tag on the client Pod.  Partial matches be prioritized by the number of tags that match.

If multiple endpoints match at the same priority, then the selection of one of them can be performed in a round robin fashion, or ClientIP affinity could be applied optionally.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/mikedanese"><img src="https://avatars3.githubusercontent.com/u/1787169?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mikedanese](https://github.com/mikedanese)**
_Thursday Oct 15, 2015 at 03:17 GMT_

----

Is there a usecase for this beyond a multi-zone cluster? Currently we recommend against multi-zone cluster for this reason (and others). See https://github.com/kubernetes/kubernetes/blob/master/docs/admin/multi-cluster.md#scope-of-a-single-cluster however it should be possible in theory. Instead we recommend a single cluster per zone (a federated model).

cc @quinton-hoole @kubernetes/goog-control-plane

**Comment by irfanurrehman** [comment]
<a href="https://github.com/davidopp"><img src="https://avatars2.githubusercontent.com/u/8264113?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davidopp](https://github.com/davidopp)**
_Thursday Oct 15, 2015 at 07:27 GMT_

----

Could you just create one service per zone, and have the pods in a zone use the service local to that zone? It seems unlikely that all the pods providing the service would go down, but the pods consuming the service would not go down, if they are all in the same zone, so I'm not sure I see a lot of value to configuring the proxy with endpoints in remote zones.

Now, if some service is _only_ available in another zone, that's another story, though the premise of your question seemed to be about a service that was available both in the local zone and a remote zone.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/eliaslevy"><img src="https://avatars1.githubusercontent.com/u/725218?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eliaslevy](https://github.com/eliaslevy)**
_Thursday Oct 15, 2015 at 15:34 GMT_

----

@mikedanese A zone is just one particular networking boundary that one may wish to use for prioritization purposes.  One may also wish to prioritize endpoints within the same node, rack, subnet, [placement group](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html), or VPC as the client.  

The proposal allows for prioritized routing of connections based on administrative policy through tags. The tags need not be related to network boundaries.  They could specify a version number with clients preferentially connecting to endpoints with a matching version number.

@davidopp You presume there is more than one Pod behind the service per network boundary or that all Pods within such boundary won't fail concurrently.  We are paid to take into account "unlikely" events and avoid them if possible.  Also note my comments above regarding boundaries other than zones. Surely you are not suggesting creating a Service per node if I wish to prioritize a node-local endpoint.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/davidopp"><img src="https://avatars2.githubusercontent.com/u/8264113?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davidopp](https://github.com/davidopp)**
_Sunday Jan 31, 2016 at 23:28 GMT_

----

@kubernetes/huawei

**Comment by irfanurrehman** [comment]
<a href="https://github.com/davidopp"><img src="https://avatars2.githubusercontent.com/u/8264113?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davidopp](https://github.com/davidopp)**
_Monday May 16, 2016 at 03:02 GMT_

----

@kubernetes/sig-cluster-federation

**Comment by irfanurrehman** [comment]
<a href="https://github.com/timothysc"><img src="https://avatars0.githubusercontent.com/u/169553?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timothysc](https://github.com/timothysc)**
_Wednesday May 18, 2016 at 19:16 GMT_

----

Doesn't this touch the longstanding topic of wanting real load-balancers with configuration and policy, as you typically adjust these types of configuration parameters? 

/cc @thockin

**Comment by irfanurrehman** [comment]
cc @eliaslevy

**Comment by craigbox** [comment]
Propose closing this and re-opening kubernetes/kubernetes#15675, as this relates to single clusters ("Ubernetes Lite"), not multi-cluster.

**Comment by davidopp** [comment]
+1, any objection?

**Comment by irfanurrehman** [comment]
Could not notice this earlier as was out of office. Closing this in favour of https://github.com/kubernetes/kubernetes/issues/15675.
