### ISSUE TITLE
include federation e2e in merge bot testing

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#46]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nikhiljindal](https://github.com/nikhiljindal)**
_Thursday Jun 02, 2016 at 17:57 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/26723_

----

We should include federation e2e in merge bot testing, so that we can catch PRs that break the test.
We need to ensure that it is 100% green before doing this.

@colhom Can you take this up?

cc @kubernetes/sig-cluster-federation

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Thursday Jun 02, 2016 at 18:02 GMT_

----

I can take this.  Lets focus on getting them all green first though.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Monday Jun 13, 2016 at 18:41 GMT_

----

@quinton-hoole can you detail the steps that are required?
It will be good to get a PR ready.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Monday Jun 13, 2016 at 18:51 GMT_

----

@nikhiljindal I don't know the precise steps offhand, but in essence there are two parts:
1. the merge-bot configuration needs to be updated to to include the "kubernetes-e2e-gce-federation" test job as a merge-blocker.  That way, if that job is failing, automated merges will be blocked.
2. the per-PR merge bot needs to be updated to deploy the federation control plane into the e2e test cluster, and add "--test_args="--ginkgo.focus=[Feature:Federation]" to the e2e tests that are run on every PR. This will ensure that the federation e2e tests are run (against a federation which includes only a single underlying cluster) for every PR.  We can extend this to multiple clusters as a second step (as this might be slightly more difficult to configure).

**Comment by irfanurrehman** [comment]
<a href="https://github.com/goltermann"><img src="https://avatars1.githubusercontent.com/u/9358478?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [goltermann](https://github.com/goltermann)**
_Monday Jun 13, 2016 at 22:11 GMT_

----

Applying P1 priority (should do for 1.3) - adjust if that's not right.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Monday Jun 13, 2016 at 22:17 GMT_

----

cc @lavalamp

**Comment by irfanurrehman** [comment]
<a href="https://github.com/lavalamp"><img src="https://avatars0.githubusercontent.com/u/647318?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lavalamp](https://github.com/lavalamp)**
_Monday Jun 13, 2016 at 23:14 GMT_

----

> the per-PR merge bot needs to be updated to deploy the federation control plane into the e2e test cluster, and add "--test_args="--ginkgo.focus=[Feature:Federation]" to the e2e tests that are run on every PR. This will ensure that the federation e2e tests are run (against a federation which includes only a single underlying cluster) for every PR. We can extend this to multiple clusters as a second step (as this might be slightly more difficult to configure)

You can only do this if it doesn't make the test take longer! Needs to stay under 30 minutes.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Monday Jun 13, 2016 at 23:23 GMT_

----

Agreed, that is part of what I meant by "more difficult" :-)

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Tuesday Jun 14, 2016 at 20:36 GMT_

----

Created a test-infra issue for the second item as per discussion with @ixdy 
https://github.com/kubernetes/test-infra/issues/155

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Thursday Aug 11, 2016 at 18:45 GMT_

----

@nikhiljindal seems to have this done.  Reassigning.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Thursday Aug 18, 2016 at 17:14 GMT_

----

This is done in kubernetes/test-infra#335. Closing.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Friday Aug 19, 2016 at 18:29 GMT_

----

Yes that PR was merged. But the test is still not passing on Jenkins. federation-apiserver pod fails to come up. I am trying to figure out how to get logs (We dont get pod logs right now)

**Comment by irfanurrehman** [comment]
<a href="https://github.com/goltermann"><img src="https://avatars1.githubusercontent.com/u/9358478?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [goltermann](https://github.com/goltermann)**
_Tuesday Sep 06, 2016 at 20:31 GMT_

----

@nikhiljindal @quinton-hoole are these passing now?  Is this issue a 1.4 blocker?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [madhusudancs](https://github.com/madhusudancs)**
_Wednesday Sep 07, 2016 at 20:28 GMT_

----

@goltermann federation tests are passing, but this issue isn't completely resolved. This isn't a 1.4 blocker. Re-targeting to 1.5.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/dims"><img src="https://avatars2.githubusercontent.com/u/23304?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dims](https://github.com/dims)**
_Wednesday Nov 16, 2016 at 14:05 GMT_

----

@madhusudancs : is this still target-ted for 1.5?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/saad-ali"><img src="https://avatars1.githubusercontent.com/u/10052848?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [saad-ali](https://github.com/saad-ali)**
_Thursday Nov 17, 2016 at 23:59 GMT_

----

@nikhiljindal @kubernetes/sig-cluster-federation I am marking this as non-release blocking for 1.5.

FYI the federation E2E suite for release-1.5 is [ci-kubernetes-e2e-gce-federation-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation-release-1.5)

**Comment by irfanurrehman** [comment]
<a href="https://github.com/nikhiljindal"><img src="https://avatars0.githubusercontent.com/u/10199099?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nikhiljindal](https://github.com/nikhiljindal)**
_Friday Nov 18, 2016 at 01:00 GMT_

----

Yes removed from 1.5 milestone

**Comment by irfanurrehman** [comment]
cc @nikhiljindal

**Comment by shashidharatd** [comment]
This is irrelevant now. federation code vendors in other repos of k8s and no longer in-tree.
Updating vendors is a manual process. We cannot put restriction on merge bot based on federation e2e tests.
/close
