### ISSUE TITLE
Address outstanding DNS review comments in #26694

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#48]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [quinton-hoole](https://github.com/quinton-hoole)**
_Monday Jun 06, 2016 at 23:42 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/26921_

----

See https://github.com/kubernetes/kubernetes/pull/26694 for details.  Specifically:
1. Don't call ensureDnsRecords() if the DNS provider has not been initialized.
2. Don't discard errors returned by getClusterZoneNames()

cc: @mfanjie FYI

**Comment by irfanurrehman** [comment]
<a href="https://github.com/goltermann"><img src="https://avatars1.githubusercontent.com/u/9358478?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [goltermann](https://github.com/goltermann)**
_Tuesday Sep 06, 2016 at 21:03 GMT_

----

@quinton-hoole this is P2...time to punt to v1.5?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Tuesday Sep 06, 2016 at 21:29 GMT_

----

@golterman Yes, 1.5 is fine.  I seem to have lost the authority to update the Milestone?  Did you perhaps change permissions?

**Comment by irfanurrehman** [comment]
<a href="https://github.com/goltermann"><img src="https://avatars1.githubusercontent.com/u/9358478?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [goltermann](https://github.com/goltermann)**
_Tuesday Sep 06, 2016 at 21:38 GMT_

----

I moved it - no idea why you wouldn't have permission on the kubernetes repo.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/dims"><img src="https://avatars2.githubusercontent.com/u/23304?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dims](https://github.com/dims)**
_Tuesday Nov 15, 2016 at 21:32 GMT_

----

ok to move this to 1.6? please holler if not appropriate

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Friday Nov 18, 2016 at 16:10 GMT_

----

Reassigning to @nikhiljindal in case he wants to address this in future.  @mfanjie would also be a suitable candidate.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/ethernetdan"><img src="https://avatars1.githubusercontent.com/u/4014393?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ethernetdan](https://github.com/ethernetdan)**
_Monday Mar 13, 2017 at 22:30 GMT_

----

Moving to 1.7 as late to happen in 1.6. Feel free to switch back if this is incorrect.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/marun"><img src="https://avatars3.githubusercontent.com/u/451477?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marun](https://github.com/marun)**
_Monday Jun 12, 2017 at 20:47 GMT_

----

Not a release blocker for 1.7.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/k8s-merge-robot"><img src="https://avatars0.githubusercontent.com/u/13653959?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [k8s-merge-robot](https://github.com/k8s-merge-robot)**
_Saturday Sep 09, 2017 at 08:01 GMT_

----

[MILESTONENOTIFIER] Milestone Removed

@nikhiljindal @quinton-hoole

**Important**:
This issue was missing labels required for the v1.8 milestone for more than 7 days:

_**kind**_: Must specify exactly one of [`kind/bug`, `kind/cleanup`, `kind/feature`].
_**priority**_: Must specify exactly one of [`priority/critical-urgent`, `priority/important-longterm`, `priority/important-soon`].

Removing it from the milestone.

<details>
Additional instructions available <a href="https://github.com/kubernetes/community/blob/master/contributors/devel/release/issues.md">here</a>
The commands available for adding these labels are documented <a href="https://github.com/kubernetes/test-infra/blob/master/commands.md">here</a>
</details>

**Comment by irfanurrehman** [comment]
cc @quinton-hoole

**Comment by shashidharatd** [comment]
The issues have been addressed in current code after it was service controller code was refactored. So this issue is not relevant anymore
/close
