### ISSUE TITLE
Move federation out of core repo

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#5]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shashidharatd](https://github.com/shashidharatd)**
_Monday Sep 25, 2017 at 14:57 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/52992_

----

This issue is to track all the tasks associated with moving out federation related code out of core `kubernetes` repo into its own repo (`k8s.io/federation`).

Refer to the plan and discussion on moving out federation in this [google doc](https://docs.google.com/document/d/1aMwWigMh7gvihqghIdqqwRRU7-LTH1erKGsHv7rCASo)

/cc @kubernetes/sig-federation-pr-reviews 
/assign @irfanurrehman

**Comment by irfanurrehman** [comment]
<a href="https://github.com/shashidharatd"><img src="https://avatars3.githubusercontent.com/u/8734900?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shashidharatd](https://github.com/shashidharatd)**
_Tuesday Oct 10, 2017 at 17:25 GMT_

----

/sig multicluster

**Comment by irfanurrehman** [comment]
<a href="https://github.com/tengqm"><img src="https://avatars1.githubusercontent.com/u/5094756?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tengqm](https://github.com/tengqm)**
_Sunday Oct 22, 2017 at 08:05 GMT_

----

/cc

**Comment by shashidharatd** [comment]
This task is complete, so closing.
/close
