### ISSUE TITLE
Refactor the getClusterZones implementations.

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#51]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [madhusudancs](https://github.com/madhusudancs)**
_Thursday Jun 23, 2016 at 19:31 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/27966_

----

There are two implementations to get the cluster zone and regions. There is one here - https://github.com/kubernetes/kubernetes/blob/6dde087f69b2bdd5f9191edbd572985e00f8c808/federation/pkg/federation-controller/cluster/cluster_client.go#L143 and the other here - https://github.com/kubernetes/kubernetes/blob/c87b61341241bae37017db5f76902ea2642ea169/pkg/dns/dns.go#L630. The two implementations must be refactored and merged.

cc @quinton-hoole @kubernetes/sig-cluster-federation

**Comment by shashidharatd** [comment]
This issue is irrelevant, getClusterZones does not exist in pkg/dns/dns.go anymore.
/close
