### ISSUE TITLE
Federation e2e tests must clean up dynamically provisioned PDs while tearing down the clusters.

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#62]
<a href="https://github.com/madhusudancs"><img src="https://avatars0.githubusercontent.com/u/10183?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [madhusudancs](https://github.com/madhusudancs)**
_Monday Aug 01, 2016 at 20:08 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/29875_

----

The `federation-apiserver`'s etcd is backed by a PVC that dynamically provisions the underlying persistent disk for its PV. We are not cleaning this up when we tear down the federation control plane and the corresponding test clusters. This caused us to run out of quota and the tests started failing.

We should delete the dynamically provisioned persistent disks at the end of the e2e tests, while tearing the clusters down.

@colhom are you seeing this behavior in your test clusters in AWS too?

cc @kubernetes/sig-cluster-federation @mml

**Comment by shashidharatd** [comment]
We are not using Dynamic PDs in the new federation jobs by default. So this issue does not exist currently federation CI jobs.
/close
