### ISSUE TITLE
federated-image.tag not found

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#66]
<a href="https://github.com/icoloma"><img src="https://avatars0.githubusercontent.com/u/222529?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [icoloma](https://github.com/icoloma)**
_Thursday Aug 18, 2016 at 12:16 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/30869_

----

Following [the documentation](http://kubernetes.io/docs/admin/federation/). With a vanilla kubernetes install, `federation-up.sh` throws an error.:

```
FATAL: tagfile /home/icoloma/code/kubernetes/cluster/../cluster/gke/../../cluster/../cluster/../federation/manifests/federated-image.tag does not exist. Make sure that you have run build/push-federation-images.sh
```

`push-federation-images.sh` works fine, but the error is still there.

**Kubernetes version**: 1.3.3
**Environment**: 
- **Cloud provider or hardware configuration**: GKE
- **OS**: 14.04.5 in my local laptop
- **Kernel**: Linux icoloma 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by irfanurrehman** [comment]
<a href="https://github.com/wattsteve"><img src="https://avatars3.githubusercontent.com/u/3201484?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wattsteve](https://github.com/wattsteve)**
_Thursday Sep 15, 2016 at 11:40 GMT_

----

I see the same thing. I'm running hack/local-up.sh and I'm following the instructions to use the official release images as I don't have a GCE account and so I don't want to build and push the images from head. I see the following error when running federation-up.sh

[root@ip-172-31-59-82 kubernetes]#  KUBERNETES_PROVIDER=aws FEDERATION_DNS_PROVIDER=aws-route53 FEDERATION_NAME=myfederation DNS_ZONE_NAME=myfederation.example FEDERATION_PUSH_REPO_BASE=gcr.io/google_containers FEDERATION=true ./federation/cluster/federation-up.sh
FATAL: tagfile /root/kubernetes/cluster/../cluster/aws/../../cluster/../cluster/../federation/manifests/federated-image.tag does not exist. Make sure that you have run build/push-federation-images.sh

**Comment by irfanurrehman** [comment]
<a href="https://github.com/wattsteve"><img src="https://avatars3.githubusercontent.com/u/3201484?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wattsteve](https://github.com/wattsteve)**
_Thursday Sep 15, 2016 at 11:41 GMT_

----

cc @kubernetes/sig-cluster-federation

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Friday Sep 16, 2016 at 20:51 GMT_

----

@colhom might be able to help

**Comment by irfanurrehman** [comment]
<a href="https://github.com/colhom"><img src="https://avatars0.githubusercontent.com/u/1075028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colhom](https://github.com/colhom)**
_Friday Sep 16, 2016 at 21:05 GMT_

----

The `federation-image.tag not found` error is usually symptomatic of `FEDERATION=true` not being set for the `build/release.sh` process, however that is actuated. @wattsteve I'm pretty sure `local-up` doesn't even use the `release.sh` script, so you'll definitely have to do this on your own.

https://github.com/kubernetes/kubernetes/blob/master/build/release.sh#L40-L46

If you want to "hack it", you can just run the contents of that `if` block in your shell (set `KUBE_ROOT=$(pwd)` first).

_obligatory hand-wavy justification for the weirdness:_ the kuberentes e2e tests are two stage (build, then e2e on a different host), so we have build stage drop the `federated-image.tag` file in the source tree so it get's carried over to the e2e tests in the build artifact tarball.

**Comment by irfanurrehman** [comment]
<a href="https://github.com/colhom"><img src="https://avatars0.githubusercontent.com/u/1075028?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [colhom](https://github.com/colhom)**
_Friday Sep 16, 2016 at 21:06 GMT_

----

\cc @icoloma

**Comment by irfanurrehman** [comment]
cc @icoloma

**Comment by shashidharatd** [comment]
This issue is irrelevant after moving the federation code and release out of core kubernetes
/close
