### ISSUE TITLE
docs for federation-controller-manager should indicate that coredns is a valid option

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#93]
<a href="https://github.com/emaildanwilson"><img src="https://avatars0.githubusercontent.com/u/3026995?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [emaildanwilson](https://github.com/emaildanwilson)**
_Wednesday Jan 11, 2017 at 19:37 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/39749_

----

https://kubernetes.io/docs/admin/federation-controller-manager/ should indicate that coredns is a valid option for --dns-provider. 

https://github.com/kubernetes/kubernetes/issues/39271#issuecomment-271783981

**Comment by shashidharatd** [comment]
This issue is already addressed.
/close
